### ISSUE TITLE
Error while loading: Cannot set SYMBOL-VALUE of *PYOBJECT-REFCOUNT-OFFSET* to NIL, not of type (MOD 1025).

### ISSUE THREAD

**Issue by digikar99** [marcoheisig/ouroboros#1]
Hi! I now have libsbcl.so and libpython3.12 on my load path. But, trying to load ouroboros causes the following error. Let me know if you can reproduce or need any additional information:

```lisp
Cannot set SYMBOL-VALUE of *PYOBJECT-REFCOUNT-OFFSET* to NIL,
not of type (MOD 1025).
   [Condition of type SIMPLE-TYPE-ERROR]

Restarts:
 0: [CONTINUE] Proceed anyway
 1: [TRY-RECOMPILING] Recompile foreign and try loading it again
 2: [RETRY] Retry loading FASL for #<CL-SOURCE-FILE "ouroboros" "foreign">.
 3: [ACCEPT] Continue, treating loading FASL for #<CL-SOURCE-FILE "ouroboros" "foreign"> as having been successful.
 4: [RETRY] Retry ASDF operation.
 5: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 --more--

Backtrace:
  0: (SB-INT:ABOUT-TO-MODIFY-SYMBOL-VALUE *PYOBJECT-REFCOUNT-OFFSET* SET NIL NIL)
      Locals:
        SB-IMPL::ACTION = SET
        SB-KERNEL:BIND = NIL
        SB-IMPL::NEW-VALUE = NIL
        SYMBOL = *PYOBJECT-REFCOUNT-OFFSET*
        SB-IMPL::VALUEP = T
  1: (SET *PYOBJECT-REFCOUNT-OFFSET* NIL)
      Locals:
        SB-IMPL::NEW-VALUE = NIL
        SYMBOL = *PYOBJECT-REFCOUNT-OFFSET*
  2: (SB-IMPL::%DEFPARAMETER *PYOBJECT-REFCOUNT-OFFSET* NIL #S(SB-C:DEFINITION-SOURCE-LOCATION :NAMESTRING "/home/user/quicklisp/local-projects/ouroboros/ouroboros/foreign.lisp" :INDICES 3080193) "Th..
      Locals:
        DOCP = T
        #:NEW = "The byte offset from the start of a Python object to its reference count."
        SOURCE-LOCATION = #S(SB-C:DEFINITION-SOURCE-LOCATION :NAMESTRING "/home/user/quicklisp/local-projects/ouroboros/ouroboros/foreign.lisp" :INDICES 3080193)
        VAL = NIL
        VAR = *PYOBJECT-REFCOUNT-OFFSET*
  3: ("top level form") [toplevel]
```

**Comment by marcoheisig** [comment]
I just pushed some updates that might fix the issue, or at least raise a proper error message.  The code for determining the refcount offset is also quite the glorious hack: https://github.com/marcoheisig/ouroboros/blob/3290cc5f9b05c0d5d27e790fe4dd349e5f981511/ouroboros/foreign.lisp#L498-L514

If the problem persists, then your Python objects must have a memory layout that is different from what I expected.  If so, can you send me the struct definition of `_object` in /usr/include/python3.12/object.h ?

Either way, I wrote this purely for performance reasons, so that I can avoid some of the calls into Python.  If this turns out to be too brittle, I can undo that optimization.

**Comment by digikar99** [comment]
Thanks! Yes, I can load ouroboros now.

```lisp
OUROBOROS> (python:|str| 2)
#<str '<COMMON-LISP:FIXNUM object at 0x71441c1061e0>'>
```

---

> Either way, I wrote this purely for performance reasons, so that I can avoid some of the calls into Python.

This is an interesting approach. I might look more carefully into where the performance loss occurs with py4cl2-cffi and might incorporate this approach.

I wonder if the brittleness could be done away with by compiling a helper C file that stores information about the offsets.
