### ISSUE TITLE
To operate well with the default multithreaded SLIME setup, python GIL should be released as soon as possible

### ISSUE THREAD

**Issue by digikar99** [marcoheisig/ouroboros#2]
In its default setting on linux (atleast, ubuntu-22.04), SLIME communicates with SBCL using multiple threads. This means, if you want to call python through threads other than the thread which loaded python, you want to release the GIL from the original thread.

```lisp
(in-package :ouroboros)

(cffi:defcfun ("PyGILState_Check" pygilstate-check) :int)
```

Upon loading ouroboros partially, `(pygilstate-check)` returns 1 and trying to hold python GIL from any other emacs buffers hangs the thread. The work around I have employed in py4cl2-cffi is to release the GIL immediately after initializing python.

Alternatively, one needs to configure SLIME/Swank to communicate with SBCL using a single thread, but that significantly defeats the purpose of using lisp.

I'm not issuing a PR because I'm not sure how you want to initialize python. In py4cl2-cffi, I'm initializing python after someone calls `(pystart)`. This will happen after py4cl2-cffi is completely loaded. The GIL too is, then, released after load time. The current ouroboros setup initializes python during load time itself.

**Comment by marcoheisig** [comment]
Good spot!  That also explains why I could use Python from Slime just fine (because it already holds the lock after initialization), but I had to acquire the lock explicitly when loading Ouroboros into Python.

I think I will do the same that you do in py4cl2-cffi and release the GIL immediately.  The problem with that is that I don't know the PyGILState.  Seems I will do again what you did in py4cl-cffi and assume a value of zero :)

At this point I want to say you another big thanks for your work with py4cl-cffi, which is an invaluable source of information!

**Comment by digikar99** [comment]
> The problem with that is that I don't know the PyGILState. Seems I will do again what you did in py4cl-cffi and assume a value of zero.

Yes, this remains a mystery. But apparantly, it has worked on Linux and Mac across x86_64 and arm64.
